// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Provider, useModel } from '/Users/wuxuegang/Study/React/aiagent/antdXStudy/src/.umi-production/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/wuxuegang/Study/React/aiagent/antdXStudy/src/.umi-production/plugin-request';
// plugins types.d.ts
export * from '/Users/wuxuegang/Study/React/aiagent/antdXStudy/src/.umi-production/plugin-antd/types.d';
export * from '/Users/wuxuegang/Study/React/aiagent/antdXStudy/src/.umi-production/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/wuxuegang/Study/React/aiagent/antdXStudy/node_modules/.pnpm/@umijs+renderer-react@4.6.54_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/Users/wuxuegang/Study/React/aiagent/antdXStudy/node_modules/.pnpm/@umijs+renderer-react@4.6.54_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/wuxuegang/Study/React/aiagent/antdXStudy/node_modules/.pnpm/umi@4.6.54_@babel+core@7.23.6_@types+node@25.8.0_@types+react@18.3.28_eslint@8.35.0_lig_55f4b9c1313fd773b51b96c8a0029342/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
