export enum ErrorCode {
  OK = 'OK',
  BAD_REQUEST = 'BAD_REQUEST',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  AI_PROVIDER_NOT_FOUND = 'AI_PROVIDER_NOT_FOUND',
  AI_MODEL_NOT_FOUND = 'AI_MODEL_NOT_FOUND',
  AI_PROVIDER_NOT_CONFIGURED = 'AI_PROVIDER_NOT_CONFIGURED',
  AI_ADAPTER_UNSUPPORTED = 'AI_ADAPTER_UNSUPPORTED',
  UPSTREAM_REJECTED = 'UPSTREAM_REJECTED',
  UPSTREAM_UNAVAILABLE = 'UPSTREAM_UNAVAILABLE',
  UPSTREAM_NETWORK_ERROR = 'UPSTREAM_NETWORK_ERROR',

  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_CREATE_FAILED = 'SESSION_CREATE_FAILED',
  MESSAGE_CREATE_FAILED = 'MESSAGE_CREATE_FAILED',

  FILE_REQUIRED = 'FILE_REQUIRED',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  FILE_TYPE_UNSUPPORTED = 'FILE_TYPE_UNSUPPORTED',
  FILE_PARSE_FAILED = 'FILE_PARSE_FAILED',

  PROVIDER_NAME_DUPLICATED = 'PROVIDER_NAME_DUPLICATED',
  CREDENTIAL_INVALID = 'CREDENTIAL_INVALID',
  MODEL_NAME_DUPLICATED = 'MODEL_NAME_DUPLICATED',
}
