// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from '/Users/wuxuegang/Study/React/aiagent/antdXStudy/src/pages/base/models/index';

export const models = {
model_1: { namespace: 'base.index', model: model_1 },
} as const
