// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","title":"示例","parentId":"@@/global-layout","id":"1"},"2":{"path":"","redirect":"/chat","parentId":"1","id":"2"},"3":{"path":"/chat","title":"Chat 聊天","parentId":"1","id":"3"},"4":{"path":"/bubble","title":"Bubble 气泡","parentId":"1","id":"4"},"5":{"path":"/welcome","title":"Welcome 欢迎","parentId":"1","id":"5"},"6":{"path":"/prompt","title":"Prompt 提示","parentId":"1","id":"6"},"7":{"path":"/think","title":"Think 思考","parentId":"1","id":"7"},"8":{"path":"/suggestion","title":"Suggestion 建议","parentId":"1","id":"8"},"9":{"path":"/sender","title":"Sender 发送","parentId":"1","id":"9"},"10":{"path":"/markdown","title":"X Markdown","parentId":"1","id":"10"},"11":{"path":"/sdk","title":"X SDK","parentId":"1","id":"11"},"12":{"path":"/card","title":"X Card","parentId":"1","id":"12"},"13":{"path":"/skill","title":"X Skill","parentId":"1","id":"13"},"14":{"path":"/ai","title":"AI","parentId":"@@/global-layout","id":"14"},"15":{"path":"","redirect":"/ai/chat","parentId":"14","id":"15"},"16":{"path":"/ai/chat","title":"Chat 聊天","parentId":"14","id":"16"},"17":{"path":"/ai/models","title":"模型管理","parentId":"14","id":"17"},"18":{"path":"/ai/files","title":"文件管理","parentId":"14","id":"18"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import('./EmptyRoute')),
'3': React.lazy(() => import(/* webpackChunkName: "p__example__chat" */'@/pages/example/chat.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__example__bubble" */'@/pages/example/bubble.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__example__welcome" */'@/pages/example/welcome.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__example__prompt" */'@/pages/example/prompt.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__example__think" */'@/pages/example/think.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__example__suggestion" */'@/pages/example/suggestion.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__example__sender" */'@/pages/example/sender.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__example__markdown" */'@/pages/example/markdown.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__example__sdk" */'@/pages/example/sdk.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__example__card" */'@/pages/example/card.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__example__skill" */'@/pages/example/skill.tsx')),
'14': React.lazy(() => import('./EmptyRoute')),
'15': React.lazy(() => import('./EmptyRoute')),
'16': React.lazy(() => import(/* webpackChunkName: "p__base__index" */'@/pages/base/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__base__models__index" */'@/pages/base/models/index.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__base__files__index" */'@/pages/base/files/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/wuxuegang/Study/React/aiagent/antdXStudy/src/layouts/index.tsx')),
},
  };
}
